// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsnjnqyuztuntutpvasf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbmpucXl1enR1bnR1dHB2YXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMjA2OTEsImV4cCI6MjA3NjY5NjY5MX0.b_w-VQpU1XF6ckIXomxgLT55MPXUBZepIsvmjcTMfYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});