// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnwethmkxoohjqsfljqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRud2V0aG1reG9vaGpxc2ZsanF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MDY4MzMsImV4cCI6MjA3Njk4MjgzM30.zan5yVFCgmp-NOykHYjbve2RnftTpeqkJhnRLlba5uA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});