name: CI-CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Run linting
        run: |
          if [ -f package.json ] && npm list --depth=0 | grep -q eslint; then
            npm run lint
          else
            echo "No linting configured, skipping..."
          fi

      - name: Run tests
        run: |
          if [ -f package.json ] && npm list --depth=0 | grep -q jest; then
            npm test
          else
            echo "No tests configured, skipping..."
          fi

      - name: Build application
        run: |
          if [ -f package.json ]; then
            npm run build --if-present
          else
            echo "No build script found, skipping..."
          fi

      - name: Security audit
        run: |
          if [ -f package.json ]; then
            npm audit --audit-level=high
          else
            echo "No package.json found, skipping security audit"
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging environment..."
        
      - name: Run integration tests
        run: echo "Running integration tests..."
        
      - name: Deploy to production
        run: echo "Deploying to production environment..."
